# Generated by Django 2.1.7 on 2019-03-21 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('config', models.TextField()),
            ],
            options={
                'db_table': 'core_ModuleConfiguration',
            },
        ),
    ]
