# Generated by Django 3.2.19 on 2023-06-01 11:45
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_set_managed_to_true'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE [tblOfficer] alter column [JsonExt] NVARCHAR(MAX)'
                          if settings.MSSQL else
                          'select 1'),
    ]
