# Generated by Django 3.2.19 on 2023-06-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0001_initial'),
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task_group',
            field=models.ForeignKey(db_column='TaskGroupID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks_management.taskgroup'),
        ),
    ]
