# Generated by Codex on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_migrate_admin_users_to_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordExpiryReminderLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password_validity", models.DateTimeField()),
                ("reminder_date", models.DateField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_expiry_reminder_logs",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "core_PasswordExpiryReminderLog",
                "managed": True,
                "unique_together": {("user", "password_validity", "reminder_date")},
            },
        ),
    ]
