# Generated by Django 4.2.29 on 2026-06-26 11:44

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models



def migrate_admin_users_to_superuser(apps, schema_editor):
    """Set is_superuser=True on Users that have an InteractiveUser assigned
    to a currently-valid (validity_to is null) Role with is_system=64.
    """
    User = apps.get_model("core", "User")
    UserRole = apps.get_model("core", "UserRole")
    Role = apps.get_model("core", "Role")

    admin_role_ids = list(
        Role.objects.filter(
            validity_to__isnull=True,
            is_system=64,
        ).values_list("id", flat=True)
    )

    if not admin_role_ids:
        return

    admin_interactive_user_ids = list(
        UserRole.objects.filter(
            validity_to__isnull=True,
            role_id__in=admin_role_ids,
        )
        .values_list("user_id", flat=True)
        .distinct()
    )

    if not admin_interactive_user_ids:
        return

    User.objects.filter(
        i_user_id__in=admin_interactive_user_ids,
    ).update(is_superuser=True)



class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0035_migrate_admin_users_to_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalUserBusinessAccess",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, editable=False
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=core.utils.uuidv7,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "date_valid_from",
                    models.DateTimeField(
                        db_column="DateValidFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "date_valid_to",
                    models.DateTimeField(
                        blank=True, db_column="DateValidTo", null=True
                    ),
                ),
                (
                    "replacement_uuid",
                    models.UUIDField(
                        blank=True, db_column="ReplacementUUID", null=True
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                ("link_type", models.CharField(blank=True, max_length=36)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User Business Access",
                "verbose_name_plural": "historical User Business Accesses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserBusinessAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        default=core.utils.uuidv7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "date_valid_from",
                    models.DateTimeField(
                        db_column="DateValidFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "date_valid_to",
                    models.DateTimeField(
                        blank=True, db_column="DateValidTo", null=True
                    ),
                ),
                (
                    "replacement_uuid",
                    models.UUIDField(
                        blank=True, db_column="ReplacementUUID", null=True
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                ("link_type", models.CharField(blank=True, max_length=36)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Business Access",
                "verbose_name_plural": "User Business Accesses",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_userbu_content_9f30b6_idx",
                    ),
                    models.Index(
                        fields=["user", "content_type", "object_id"],
                        name="core_userbu_user_id_628c07_idx",
                    ),
                    models.Index(
                        fields=["user", "link_type"],
                        name="core_userbu_user_id_57d1ee_idx",
                    ),
                    models.Index(
                        fields=["link_type", "object_id"],
                        name="core_userbu_link_ty_196d04_idx",
                    ),
                ],
            },
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                core.utils.CachedModelMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(
            migrate_admin_users_to_superuser,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
