# Generated by Django 4.2.28 on 2026-02-20 09:06

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0035_migrate_admin_users_to_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinteractiveuser",
            name="uuid",
            field=models.UUIDField(
                db_column="UUID",
                db_index=True,
                default=core.utils.uuidv7,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="uuid",
            field=models.UUIDField(
                db_column="UUID", default=core.utils.uuidv7, editable=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="HistoricalUserBusinessAccess",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, editable=False
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        db_index=True,
                        default=core.utils.uuidv7,
                        editable=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "date_valid_from",
                    models.DateTimeField(
                        db_column="DateValidFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "date_valid_to",
                    models.DateTimeField(
                        blank=True, db_column="DateValidTo", null=True
                    ),
                ),
                (
                    "replacement_uuid",
                    models.UUIDField(
                        blank=True, db_column="ReplacementUUID", null=True
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User Business Access",
                "verbose_name_plural": "historical User Business Accesses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserBusinessAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "uuid",
                    models.UUIDField(
                        db_column="UUID",
                        default=core.utils.uuidv7,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "json_ext",
                    models.JSONField(blank=True, db_column="Json_ext", null=True),
                ),
                ("date_deactivated", models.DateTimeField(default=None, null=True)),
                (
                    "date_valid_from",
                    models.DateTimeField(
                        db_column="DateValidFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "date_valid_to",
                    models.DateTimeField(
                        blank=True, db_column="DateValidTo", null=True
                    ),
                ),
                (
                    "replacement_uuid",
                    models.UUIDField(
                        blank=True, db_column="ReplacementUUID", null=True
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Business Access",
                "verbose_name_plural": "User Business Accesses",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_userbu_content_9f30b6_idx",
                    )
                ],
            },
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                core.utils.CachedModelMixin,
                models.Model,
            ),
        ),
    ]
