# Generated by Django 4.2.29 on 2026-06-02 14:03

from django.db import migrations, models


def migrate_admin_users_to_superuser(apps, schema_editor):
    """Set is_superuser=True on Users that have an InteractiveUser assigned
    to a currently-valid (validity_to is null) Role with is_system=64.
    """
    User = apps.get_model("core", "User")
    UserRole = apps.get_model("core", "UserRole")
    Role = apps.get_model("core", "Role")

    admin_role_ids = list(
        Role.objects.filter(
            validity_to__isnull=True,
            is_system=64,
        ).values_list("id", flat=True)
    )

    if not admin_role_ids:
        return

    admin_interactive_user_ids = list(
        UserRole.objects.filter(
            validity_to__isnull=True,
            role_id__in=admin_role_ids,
        )
        .values_list("user_id", flat=True)
        .distinct()
    )

    if not admin_interactive_user_ids:
        return

    User.objects.filter(
        i_user_id__in=admin_interactive_user_ids,
    ).update(is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_historicalinteractiveuser_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddIndex(
            model_name="userbusinessaccess",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="core_userbu_user_id_628c07_idx",
            ),
        ),
        migrations.RunPython(
            migrate_admin_users_to_superuser,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
