# Generated by Django 4.2.29 on 2026-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_historicalinteractiveuser_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddIndex(
            model_name="userbusinessaccess",
            index=models.Index(
                fields=["user", "content_type", "object_id"],
                name="core_userbu_user_id_628c07_idx",
            ),
        ),
    ]
