# Generated by Django 4.2 on 2026-09-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0037_historicaluser_is_superuser_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RightPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "right_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="The openIMIS identifier the roles carry. Not unique: several actions may share one right.",
                    ),
                ),
                (
                    "permission",
                    models.OneToOneField(
                        help_text="The django permission, reused as is when it already exists.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openimis_right",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "right / permission mapping",
                "verbose_name_plural": "right / permission mappings",
                "db_table": "core_RightPermission",
            },
        ),
    ]
