# Generated by Django 4.2.29 on 2026-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_historicaluser_is_superuser_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserbusinessaccess",
            name="link_type",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="userbusinessaccess",
            name="link_type",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddIndex(
            model_name="userbusinessaccess",
            index=models.Index(
                fields=["user", "link_type"], name="core_userbu_user_id_57d1ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbusinessaccess",
            index=models.Index(
                fields=["link_type", "object_id"], name="core_userbu_link_ty_196d04_idx"
            ),
        ),
    ]
