# Generated by Django 4.2.30 on 2026-08-27 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid
import uuid6


def _backfill_uuid(apps, model_name):
    model = apps.get_model('core', model_name)
    rows = []
    for row in model.objects.filter(uuid__isnull=True).only('pk', 'uuid').iterator():
        row.uuid = uuid6.uuid7()
        rows.append(row)
    model.objects.bulk_update(rows, ['uuid'], batch_size=500)


def backfill_roleright_uuid(apps, schema_editor):
    _backfill_uuid(apps, 'RoleRight')


def backfill_userrole_uuid(apps, schema_editor):
    _backfill_uuid(apps, 'UserRole')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_historicaluser_is_superuser_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='date_deactivated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='Json_ext', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roleright',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roleright',
            name='date_deactivated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='roleright',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='Json_ext', null=True),
        ),
        migrations.AddField(
            model_name='roleright',
            name='uuid',
            field=models.UUIDField(db_column='UUID', editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_roleright_uuid, migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name='roleright',
            name='uuid',
            field=models.UUIDField(db_column='UUID', default=uuid6.uuid7, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='roleright',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrole',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='date_deactivated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='Json_ext', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='uuid',
            field=models.UUIDField(db_column='UUID', editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_userrole_uuid, migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uuid',
            field=models.UUIDField(db_column='UUID', default=uuid6.uuid7, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='validity_to',
            field=models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='roleright',
            name='validity_to',
            field=models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='validity_from',
            field=models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='validity_to',
            field=models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalUserRole',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(db_column='UUID', db_index=True, default=uuid6.uuid7, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_deactivated', models.DateTimeField(default=None, null=True)),
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True)),
                ('id', models.IntegerField(blank=True, db_column='UserRoleID', db_index=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AudituserID', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.role')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.interactiveuser')),
            ],
            options={
                'verbose_name': 'historical user role',
                'verbose_name_plural': 'historical user roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoleRight',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(db_column='UUID', db_index=True, default=uuid6.uuid7, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_deactivated', models.DateTimeField(default=None, null=True)),
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True)),
                ('id', models.IntegerField(blank=True, db_column='RoleRightID', db_index=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('right_id', models.IntegerField(db_column='RightID')),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserId', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.role')),
            ],
            options={
                'verbose_name': 'historical role right',
                'verbose_name_plural': 'historical role rights',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRole',
            fields=[
                ('version', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_deactivated', models.DateTimeField(default=None, null=True)),
                ('validity_from', models.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now, null=True)),
                ('validity_to', models.DateTimeField(blank=True, db_column='ValidityTo', default=None, null=True)),
                ('id', models.IntegerField(blank=True, db_column='RoleID', db_index=True)),
                ('uuid', models.CharField(db_column='RoleUUID', db_index=True, default=uuid.uuid4, max_length=36)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('name', models.CharField(db_column='RoleName', max_length=50)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=50, null=True)),
                ('is_system', models.IntegerField(db_column='IsSystem')),
                ('is_blocked', models.BooleanField(db_column='IsBlocked')),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical role',
                'verbose_name_plural': 'historical roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
