# Generated by Django 4.2.29 on 2026-06-19 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_historicaluserbusinessaccess_link_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinteractiveuser",
            name="validity_from",
            field=models.DateTimeField(
                db_column="ValidityFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AlterField(
            model_name="historicalinteractiveuser",
            name="validity_to",
            field=models.DateTimeField(blank=True, db_column="ValidityTo", null=True),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="validity_from",
            field=models.DateTimeField(
                db_column="ValidityFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AlterField(
            model_name="interactiveuser",
            name="validity_to",
            field=models.DateTimeField(blank=True, db_column="ValidityTo", null=True),
        ),
        migrations.AlterField(
            model_name="technicaluser",
            name="validity_from",
            field=models.DateTimeField(
                db_column="ValidityFrom", default=datetime.datetime.now
            ),
        ),
        migrations.AlterField(
            model_name="technicaluser",
            name="validity_to",
            field=models.DateTimeField(blank=True, db_column="ValidityTo", null=True),
        ),
    ]
