# Generated by Django 4.2.30 on 2026-08-27 09:27

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_backfill_role_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='uuid',
            field=models.CharField(db_column='RoleUUID', db_index=True, default=core.models.user.role_uuid_default, max_length=36),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.CharField(db_column='RoleUUID', default=core.models.user.role_uuid_default, max_length=36, unique=True),
        ),
    ]
